src/app/layout.tsx, src/components/global/LogoutButton.tsx, src/components/global/Navbar.tsx, src/components/skeleton/NavbarSkeleton.tsx, src/components/ui/skeleton.tsx
se añadió el botón de cerrar sesión
=> Task 119 navbar clientes

src/components/pets/PetForm.tsx, src/lib/pets/getRacesAndSpecies.ts
Correciones:
- Ahora el campo de fecha de nacimiento no permite seleccionar fechas futuras.
- Botón "Cancelar" redirige correctamente al perfil del usuario.
- Ahora las razas se filtran dinámicamente según la especie seleccionada, evitando combinaciones incorrectas.
=> TASK-122-RegistroMascota

cypress.config.ts, cypress/e2e/register-pet.cy.ts, src/components/pets/PetForm.tsx
Llevar a cabo una prueba sobre el registro de mascotas:
- Utilizando datos inválidos
- Datos Validos
- Verificar redireccionamiento
- Verificar caso de success
- Uso de Credenciales
- Interceptación de peticiones
=> [200] Test e2e registro mascotas

src/app/forgot-password/page.tsx, src/app/login/page.tsx, src/app/register/page.tsx, src/app/reset-password/page.tsx
Actualizacion del campo contraseña, ahora verifica si la longitud de la contraseña
=> Task 114 pantalla de registro

cypress/e2e/user-profile.cy.ts
Llevar a cabo pruebas sobre la pantalla de Perfil de Usuario:
-Inicio de sesión: Acceder al perfil del usuario.
-Verificación del perfil: Confirmar que la información del usuario se muestre correctamente.
-Navegación: Verificar el acceso a las secciones "Agregar Mascota" y "Ver lista de mascotas".
-Interacción con mascotas: Comprobar la presencia de tarjetas de mascotas y acceder a los detalles de la primera.
=> [203]-Test-e2e-sobre-Perfil-Usuario

src/components/petUI/PetDetails.tsx
Manejo en caso de mascota no existente (404)
=> Task 124 fe detalle de mascota

cypress/e2e/listado-mascotas.cy.ts
Llevar a cabo pruebas sobre el Listado de Mascotas:
- Login y verificación de perfil.
- Navegación hacia la lista de mascotas.
- Verificación de la visualización de las mascotas (en formato cuadriculado o lista).
- Filtrado de mascotas y limpieza del filtro.
- Navegación entre páginas de la lista de mascotas.
- Verificación de detalles de mascota.
- Verificación del mensaje de "Lista vacía" cuando el usuario no tiene mascotas.
=> [206]-Test-e2e-Listado-Mascotas

src/components/petUI/PetDetails.tsx, src/components/petUI/PetList.tsx, src/lib/auth/options.ts, src/lib/env.ts, src/lib/pets/getPetsByUserId.ts, src/lib/pets/getRaces.ts, src/lib/pets/getRacesAndSpecies.ts, src/lib/pets/registerPet.ts, src/lib/urls.ts
Archivo "env.ts":
- Contiene las variables de entorno BASE_URL (para la API) y NEXTAUTH_SECRET (para la autenticación).
Archivo "urls.ts":
- Contiene las rutas de la API, construidas a partir de la BASE_API_URL
=> [210]-FE-modularizar-variables-entorno

src/components/global/Card.tsx
- Se unificaron los componentes `ProductCard` y `ServiceCard` en un único `Card` flexible y reutilizable.  
- Se agregaron nuevas propiedades:  
- `layout`: permite cambiar entre diseño "vertical" u "horizontal".  
- `imagePosition`: permite colocar la imagen en "top", "bottom", "left" o "right".  
- `showButton`: permite ocultar el botón si no es necesario.  
- `bgColor` y `textColor`: permiten personalizar los colores de fondo y texto usando Tailwind.  
- `children`: reemplaza `buttonComponent`, permitiendo agregar cualquier contenido adicional.  
- Se agregaron ejemplos con diferentes estilos de botones.  
- Probados en página de test
=> [TASK 167] Unificación y mejora del componente Card

src/app/not-found.tsx
Redireccionamiento para "Regresar a la página de inicio"
=> [211]-redireccionamiento

src/app/dashboard/page.tsx, src/components/admin/Header.tsx
Componente reutilizable para mostrar el nombre y apellido del administrador autenticado
=> [236]-AdminHeader

src/components/pets/PetForm.tsx
- Ya no permite ingresar numeros negativos en el form
=> Task-173-FE-Registro-de-Mascota-para-subida-de-archivos

src/app/dashboard/layout.tsx, src/app/dashboard/page.tsx, src/components/admin/Header.tsx
Header responsive
Dashboard modificación para traer datos del usuario logeado
=> [236]-header-responsive

src/app/login/page.tsx
Redireccionar a /user-profile si tiene rol USER y a /dashboard si tiene rol ADMIN
=> [243]-login-redireccionamiento-segun-rol

src/app/dashboard/products/[id]/page.tsx, src/components/admin/product/ProductDetail.tsx, src/components/admin/product/ProductFilter.tsx, src/components/admin/product/ProductList.tsx, src/lib/admin/products/getProductById.ts
Página en el panel de administración para mostrar el producto seleccionado con mayor detalles y opciones de edicion o eliminacion.
=> Task 218 producto detalle admin

src/components/admin/vaccine/VaccineList.tsx
solo agregué un botón con redirección a agregar nuevo fabricante, nada grave
=> agregué botón para direccionar a sección de nuevo fabricante de vacunas

package.json, pnpm-lock.yaml, src/components/admin/product/ProductDetail.tsx, src/components/admin/product/ProductFilter.tsx, src/components/admin/product/ProductList.tsx, src/lib/admin/products/useDebounceHook.ts
Filtros funcionalidad cambiada y renderización
=> Task 217 lista productos admin

src/app/dashboard/stock/register/page.tsx, src/components/stock/register/StockForm.tsx, src/lib/stock/IStock.ts, src/lib/stock/registerStock.ts, src/lib/urls.ts
ojala ya ande el deploy pipipi
=> Task 233 crear deposito

src/components/admin/work-position/PositionForm.tsx, src/lib/work-position/getPositionById.ts, src/lib/work-position/registerPosition.ts, src/lib/work-position/updatePosition.ts
=> Task 228 fe puestos crear editar

src/components/admin/product/ProductDetail.tsx, src/components/admin/product/ProductList.tsx
Redireccionamiento de botón Crear y Editar Producto
=> [217]-redireccionamiento

src/components/admin/work-position/PositionForm.tsx, src/components/profile/PetLists.tsx, src/lib/client/getUsers.ts, src/lib/pets/getPetsByUserId.ts
=> TASK-228-FE-Puestos-Crear-Editar

src/components/petUI/PetList.tsx, src/lib/pets/getPetsByUserId.ts
Utilizar imágenes de la respuesta de la API para las mascotas. [ :heavy_check_mark: ]
Cambiar estilos de la carta para los casos de cuadricula o lista de forma de que tenga una mayor consistencia con el resto de la app. [ :heavy_check_mark: ]
En el buscador se debe filtrar por el backend. [ :heavy_check_mark: ]
=> [290] Bugfix de petlist

src/components/petUI/PetDetails.tsx
-  La imagen se maneja como un objeto en vez de como un string.
- Se reutilizan funciones definidas en la carpeta lib "IPet","getPetById" y "updatePet" para obtener y actualizar la información de la mascota.
=> Task 289 IMAGE en detalle mascota

src/components/employee/register/EmployeeForm.tsx, src/lib/employee/IEmployee.ts, src/lib/employee/getEmployees.ts, src/lib/employee/registerEmployee.ts
anhadi campos de numero de telefono y direccion, tambien valida el numero y el ruc
=> Task 307 bug employee register

src/app/user-profile/page.tsx, src/app/user-profile/pet/register/page.tsx, src/components/pet/PetForm.tsx, src/components/profile/PetLists.tsx, src/lib/pets/getPetsByUserId.ts
- Se cambió userId por clientId registrar mascota y perfil de usuario
=> Task 303 bug fe user profile pet register

src/components/employee/register/EmployeeForm.tsx
solucion al seleccionar un puesto, ya no aparece el mensaje de advertencia que hay que seleccionar un puesto, de paso mejore el manejo de la imagen
=> validacion al elegir un puesto

src/components/admin/provider/ProviderList.tsx, src/components/admin/provider/skeleton/ProviderTableSkeleton.tsx, src/components/admin/settings/SettingsList.tsx, src/lib/provider/IProvider.ts, src/lib/provider/deleteProviderById.ts, src/lib/provider/getProviders.ts
El listado hace uso de los componentes de searchbar y paginación, también confirma el borrado mediante un modal, se usa skeleton para la carga de la lista y se implementa con el modal de detalles de proveedores
=> [274] Listado de proveedores (admin)

src/app/dashboard/settings/species/page.tsx, src/components/admin/settings/species/SpeciesList.tsx, src/components/admin/settings/species/skeleton/SpecieTableSkeleton.tsx, src/lib/pets/deleteSpecieById.ts, src/lib/pets/registerSpecies.ts, src/lib/pets/updatePet.ts, src/lib/pets/updateSpecie.ts
implementacion de las funciones en SpeciesList
Implementacion de ConfirmationModal
se creo la pagina en la ubicacion /dashboard/settings/species
se listan las especies, se puede buscar filtrando por nombre y se puede eliminar una especie con el basurero.
=> creacion de las paginas necesarias

src/app/dashboard/layout.tsx, src/app/dashboard/page.tsx, src/components/global/Navbar.tsx
el navbar desaparece cuando un admin entra al programa
=> Task 254 modificacion layout

src/components/admin/client/ClientList.tsx, src/components/admin/product/filter/ProductFilter.tsx, src/components/admin/provider/ProviderList.tsx, src/components/admin/settings/races/RaceList.tsx, src/components/admin/settings/species/SpeciesList.tsx, src/components/admin/settings/tags/TagList.tsx, src/components/admin/vaccine-manufacturer/ManufacturerList.tsx, src/components/admin/vaccine/VaccineList.tsx, src/components/admin/work-position/WorkPositionList.tsx, src/components/global/SearchBar.tsx, src/components/pet/PetList.tsx
Aviso que modifiqué (para eliminar manual search nomas):
- PetList
- ClientList
- ProductFilters
- ProviderList
- RaceList
- SpeciesList
- TagList
- VaccineList
- ManufacturerList
- WorkPosition
Falta cambiar el componente de:
- Deposit List
- Employee List
=> Task256 estandarizar barra de busqueda

src/app/dashboard/purchases/register/page.tsx, src/components/admin/purchases/PurchaseForm.tsx, src/components/admin/purchases/PurchaseItemSearch.tsx, src/components/admin/purchases/PurchaseItems.tsx, src/components/admin/purchases/skeleton/PurchaseSearchSkeleton.tsx, src/hooks/purchases/useProductSearch.tsx, src/hooks/purchases/useProviderStock.tsx, src/hooks/purchases/usePurchase.tsx, src/lib/purchases/IPurchase.ts, src/lib/purchases/purchaseSchema.ts, src/lib/purchases/registerPurchase.ts, src/lib/urls.ts
Se agrega la funcionalidad para crear compras que actualizan el stock de productos.
Formulario con los campos requeridos por la API:
-Proveedor
-Depósito afectado
-Fecha de la operación
-Productos y cantidades
=> Task 280 fe crear compras admin

src/components/deposit/DepositList.tsx
=> implementacion de busqueda automatica con componente searchBar global

src/components/employee/EmployeeList.tsx
uso del searchbar generico en employeelist
=> TASK 316 - Uso de searchbar generico Employee

src/app/user-profile/page.tsx
correccion del searchBar.
deshabilitacion del buscado manual e implementacion del automatico
=> Task 265 fe lista de especies

src/components/admin/purchases/PurchaseForm.tsx
permite seleccionar fechas anteriores
=> permite seleccionar fechas anteriores

src/components/admin/movements/MovementEmployeeSelected.tsx, src/components/admin/movements/MovementStockSelector.tsx, src/components/admin/movements/register/MovementForm.tsx
al enviar el formulario, no permite eliminar producto ni empleado, se bloquean todos los campos
los select de depositos se setean cuando se cambia el tipo de movimiento (si es que previamente fue seleccionado alguno)
=> Task 273 fe form movimientos de stock

src/app/dashboard/clients/[id]/pet/[petId]/edit/page.tsx, src/app/dashboard/clients/[id]/pet/[petId]/page.tsx, src/lib/pets/getPetById.ts
Modificado, ya trae notFound en id no registrada
=> Bug corregido

src/components/deposit/DepositList.tsx, src/components/stock/register/StockForm.tsx
Tras revisar, el apartado de paginacion funciona correctamente, solo que no habia la suiciente cantidad de depositos para que se activara (16)
no se notaba al agregar un nuevo deposito porque la pagina no se refrescaba tras completar el formulario.
Cambios:
-se actualizo StockForm para que se actualice la pagina tras crear o editar un deposito
=> Correccion del Error en dashboard/stock

src/app/about/page.tsx, src/components/admin/client/ClientList.tsx, src/lib/client/deleteClient.ts
Elimina de la lista  al cliente elegido. aparece un modal de confirmacion, aparece el mensaje toast
=> Task-337-eliminar-cliente

src/components/admin/movements/MovementList.tsx, src/lib/movements/getMovements.ts
se modifico getMovements para que tenga en cuenta los diferentes tipos de error y lanze el error especifico.
se modifico MovementList para que agarre los errores y muestre un toast respectivo para ellos. se borro el mensaje de error dentro de la lista para hacer uso unicamente de toast.
=> Se aplicaron cambios para que La Pagina Movements muestre errores especificos

src/components/deposit/DepositCard.tsx, src/components/deposit/DepositList.tsx, src/components/stock/register/StockForm.tsx
-se corrigio el error que causaba que al abrir el form para registrar un deposito aparecia con los datos del ultimo deposito editado
-Se cambio el color del icono de Basurero Rojo->Negro
-Se elimino el emoji de confirmacion de los mensajes del Toast
=> se aplicaron los cambios requeridos por la Tester

.hintrc, src/components/admin/movements/MovementCard.tsx, src/components/admin/purchases/PurchaseCard.tsx, src/components/admin/purchases/detailCard/PurchaseProviderCard.tsx, src/components/pet/PetDetails.tsx, src/lib/utils.ts
Se actualizo la función que estaba en lib/utils para mostrar las fechas en el formato esperado y se actualizaron las pantallas de listar y detalles que enseñaban fechas para que utilicen la función mencionada.
=> Estandarización de fechas en la app

src/components/admin/product/ProductRegister.tsx, src/components/admin/product/filter/NumericFilter.tsx, src/components/admin/purchases/filters/PurchaseNumericFilter.tsx, src/components/admin/vaccine/NewVaccineForm.tsx, src/components/global/NumericInput.tsx
cambiado en productos, vacunas y compras filtros
=> Task355 fe formateo de digitos numericos en inputs

src/components/admin/movements/MovementFilters.tsx, src/hooks/movements/useMovementList.ts
aplicacion de toast en movementFilters, comprobacion del tipo de error en useMovementList
=> cambios de uso de console.error en movementFilters
